### ISSUE TITLE
Highlight selected line

### ISSUE THREAD

**Issue by Shatur** [krady21/compiler-explorer.nvim#1]
Mentioned https://github.com/p00f/godbolt.nvim [highlights the selected line](https://github.com/p00f/godbolt.nvim)(see from 19 sec).
Could you add the same feature?

**Comment by krady21** [comment]
Hi. I think you may have sent the same link twice there. If you refer to source to assembly and assembly to source line highlighting (as it happens on the compiler explorer website) then the feature is already supported. All you have to do is add
 `open_qflist = true` to the setup function. I am sorry if the documentation is not yet up to par, but I haven't had the chance to add some vimdocs or a features section to the README just yet. Let me know if this is the feature you were referring to.

**Comment by Shatur** [comment]
Oh, got, thank you!

**Comment by Shatur** [comment]
@krady21 I tried setting

```lua
require("compiler-explorer").setup({
  open_qflist = true,
})
```

But it stopped to use Telescope for selection.

**Comment by krady21** [comment]
oops, my bad. I meant to give give you another option: 
```lua
require("compiler-explorer").setup({
  autocmd = {
    enable = true,
    hl = "Search",
  }
})
```
The enable is the important part, while hl allows you to change the highlight group. I think that i am using `CursorLine` as the default highlight group so that it would match well if you have the `set cursorline` option on.

`open_qflist = true` opens the quickfix list which should be populated by the errors, warnings and diagnostics received from compiler-explorer.

**Comment by Shatur** [comment]
> I meant to give give you another option:

Same here, with this configuration I losing selection through Telescope. Is this expected?

**Comment by Shatur** [comment]
Without any configuration `:CECompile` opens selection (expected!):
![изображение](https://user-images.githubusercontent.com/22453358/189178700-495b5075-e446-4f8d-9073-32e00658977a.png)

But if I call `setup()` selection looks like this after calling `:CECompile`:
![изображение](https://user-images.githubusercontent.com/22453358/189179084-a5f903c9-91f5-44b6-bb17-7d29bb8e2184.png)

**Comment by krady21** [comment]
Sorry for the late reply. I could not reproduce this with telescope and by running the `setup()` function. The setup code does not interfere with the other plugins that override `vi.ui`, so I'm not exactly sure why this happens. Maybe you resourcing your init.lua or init.vim switches back to the default `vim.ui.select`.

**Comment by Shatur** [comment]
> Sorry for the late reply. I could not reproduce this with telescope and by running the setup() function. The setup code does not interfere with the other plugins that override vi.ui, so I'm not exactly sure why this happens

I think I know why it happens. These lines:
https://github.com/krady21/compiler-explorer.nvim/blob/c21396d924bda4fc0e087e7929fce69883aa0527/lua/compiler-explorer/init.lua#L13-L14
cache `vim.ui.select`. And in my case `vim.ui.select` initializes after it if I call `setup` because file is being loaded.

**Comment by Shatur** [comment]
Opened #4.
