### ISSUE TITLE
[ Feature ] If first compilation is faild, the `CECompileLive` wont create autocmd `BufWritePost`

### ISSUE THREAD

**Issue by NEX-S** [krady21/compiler-explorer.nvim#14]
If the first compilation by `CECompileLive` fails, the `CECompileLive` won't create autocmd `BufWritePost`.
which it's a little inconvenient.

and seems there's no option can control the quickfix-window popup. I'd rather use the virtual text to indicate the error, don't really need quickfix-window ( might block our sight)

**Comment by krady21** [comment]
Hi. Thanks for opening this issue.
Regarding the first problem with CECompileLive, that seems like bad design on my part. I'll see what i can do about it.
There used to be an open_qflist option, but I removed it in a previous commit. I did not now if people were using it or not. I'll bring it back.
