### ISSUE TITLE
Add the select language, compiler and flags from command

### ISSUE THREAD

**Issue by Shatur** [krady21/compiler-explorer.nvim#2]
Currently the plugin opens a fuzzy finder for each step, but it would be nicer to have the ability to pass all parameters from command window. This would allow to avoid selecting the same stuff when you changing flags, for example. Neovim supports custom commands completion, so using it would be very convenient.

**Comment by krady21** [comment]
Hi. I've been thinking about adding this, but I wanted to first prioritize the interactive approach implementation. My rationale was that `vim.ui.select|input` could be the difference maker between this neovim plugin and the other editor plugins found [here](https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/API.md#implementations). I'll look into it.

**Comment by krady21** [comment]
This should work now. Let me know how you feel about the current form. 
```vim
:CECompile compiler=g121 flags=-O2 intel=false
```
I will also add command completion for the compiler ids in a future commit.

**Comment by Shatur** [comment]
Thank you! I like this feature.
