### ISSUE TITLE
How to specify compiler for the languages "c++"

### ISSUE THREAD

**Issue by ShangjinTang** [krady21/compiler-explorer.nvim#20]
This is a very good nvim extension and I am using it everyday recently.

Issue: I want to specify the c++ compiler as below

```lua
require("compiler-explorer").setup({
    -- url = "https://godbolt.org",
    url = "http://localhost:8888",
    languages = { -- Language specific default compiler/flags
        c++ = {
            compiler = "clang++default",
            compiler_flags = "-O0 -Wall -pedantic -fno-exceptions -std=c++20",
        },
    },
})
```

**But lua does not support `+` in language name such as `c++`. I have tried to change it to `cpp`, also not work.** 

Is there any way to solve this? Looking forward for your reply.

**Comment by krady21** [comment]
Hi. Thanks for the kind words. I think you can specify table keys with special characters by using different syntax. This should work:
```lua
require("compiler-explorer").setup({
    -- url = "https://godbolt.org",
    url = "http://localhost:8888",
    languages = { -- Language specific default compiler/flags
        ["c++"] = {
            compiler = "clang++default",
            compiler_flags = "-O0 -Wall -pedantic -fno-exceptions -std=c++20",
        },
    },
})
```

**Comment by ShangjinTang** [comment]
Many thanks! It solves my issue perfectly.
