### ISSUE TITLE
Do no cache vim.ui

### ISSUE THREAD

**Issue by Shatur** [krady21/compiler-explorer.nvim#4]
The plugin currently cache vim.ui. functions:
https://github.com/krady21/compiler-explorer.nvim/blob/c21396d924bda4fc0e087e7929fce69883aa0527/lua/compiler-explorer/init.lua#L13-L14
In my configuration if I call setup before initializing https://github.com/stevearc/dressing.nvim - it uses old `vim.ui.*`.

**Comment by krady21** [comment]
Nice catch. Should be solved now :)
